### get all artifacts
GET http://localhost:8080/api/artifact

### create an artifact
POST http://localhost:8080/api/artifact
Content-Type: application/json

{
  "title": "Portrait of an old man",
  "description" : "'Portrait of an Old Man' after Rembrandt van Rijn is a painting that explores the artist's fascination with old age and character studies, often referred to as a 'tronie,' and is known for its realistic, expressive, and psychologically dense portrayal. ",
  "category" : "Painting",
  "artist" : "After Rembrandt van Rijn",
  "location": "Van Tilburg Gallery, Old Arts 2-10",
  "date": "1830-01-01"
}

### get all artifacts by categoryId
GET http://localhost:8080/api/artifact/category/1